
cc_library(
    name='cc_lib',
    srcs = glob(['*.cpp']),
    hdrs = glob(['*.h']),
    deps = ['//messageLib:cc_lib','//transportService:cc_lib',],
    visibility = ['//driver:__pkg__',],
    includes = ['.'],
)
